strategy: 6a
real_train_path: real_data_summarized_four_splits/training_data
real_val_path: real_data_summarized_four_splits/val_data
real_test_path: null
synthetic_base_path: null
synthetic_test_path: null
from_scratch: false
initial_lr: 0.0001
batch_size: 32
num_workers: 4
max_epochs: 100
early_stopping_patience: 20
mimic_mean: null
mimic_std: null
compute_normalization: true
output_dir: outputs_summarized/downstream_eval
chexpert_csv_path: src/1_prepare_chexpert/chexpert_filtered.csv
chexpert_image_base_path: /mnthpc/netapp01/projects/AI4Health/sourcedata/Chest Xray/ChexPert/chexpertchestxrays-u20210408/unzipped_latest/
evaluate_on_chexpert: false
